//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetSporWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAntreman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAntreman()
        {
            this.tblAntremanAyrinti = new HashSet<tblAntremanAyrinti>();
        }
    
        public int antremanid { get; set; }
        public Nullable<int> antrenorid { get; set; }
        public Nullable<int> kullaniciid { get; set; }
        public Nullable<System.DateTime> antremanBaslamaTarih { get; set; }
        public Nullable<bool> antremanAktiflik { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
        public virtual tblKullanici tblKullanici1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAntremanAyrinti> tblAntremanAyrinti { get; set; }
    }
}
