//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetSporWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiyet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDiyet()
        {
            this.tblDiyetAyrinti = new HashSet<tblDiyetAyrinti>();
        }
    
        public int diyetid { get; set; }
        public Nullable<int> kullaniciid { get; set; }
        public Nullable<int> diyetistenid { get; set; }
        public Nullable<System.DateTime> diyetBaslamTarihi { get; set; }
        public Nullable<bool> diyetAktiflik { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
        public virtual tblKullanici tblKullanici1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiyetAyrinti> tblDiyetAyrinti { get; set; }
    }
}
