//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetSporWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiyetAyrinti
    {
        public int diyetAyrintiid { get; set; }
        public Nullable<int> diyetiid { get; set; }
        public Nullable<System.DateTime> diyetgun { get; set; }
        public Nullable<int> menuid { get; set; }
    
        public virtual tblDiyet tblDiyet { get; set; }
        public virtual tblMenu tblMenu { get; set; }
    }
}
