//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetSporWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKullanici()
        {
            this.tblAntreman = new HashSet<tblAntreman>();
            this.tblAntreman1 = new HashSet<tblAntreman>();
            this.tblBlog = new HashSet<tblBlog>();
            this.tblDiyet = new HashSet<tblDiyet>();
            this.tblDiyet1 = new HashSet<tblDiyet>();
            this.tblislemler = new HashSet<tblislemler>();
            this.tblMesaj = new HashSet<tblMesaj>();
            this.tblMesaj1 = new HashSet<tblMesaj>();
            this.tblTalep = new HashSet<tblTalep>();
            this.tblTalep1 = new HashSet<tblTalep>();
        }
    
        public int kullaniciid { get; set; }
        public long kullaniciTc { get; set; }
        public string kullaniciAd { get; set; }
        public string kullaniciSoyad { get; set; }
        public Nullable<bool> kullaniciCinsiyet { get; set; }
        public Nullable<System.DateTime> kullaniciDogumTarihi { get; set; }
        public string kullaniciEmail { get; set; }
        public int kullaniciSifre { get; set; }
        public Nullable<long> kullaniciTelefon { get; set; }
        public Nullable<int> kullaniciBilgiDetayid { get; set; }
        public string kullaniciTipi { get; set; }
        public Nullable<System.DateTime> kullaniciKayitTarihi { get; set; }
        public Nullable<int> kullaniciPuan { get; set; }
        public Nullable<bool> kullaniciHesapAKtiflik { get; set; }
        public Nullable<bool> kullaniciDanismanDurum { get; set; }
        public Nullable<int> kullaniciDanismanid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAntreman> tblAntreman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAntreman> tblAntreman1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBlog> tblBlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiyet> tblDiyet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiyet> tblDiyet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblislemler> tblislemler { get; set; }
        public virtual tblKullaniciBilgi tblKullaniciBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesaj> tblMesaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesaj> tblMesaj1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTalep> tblTalep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTalep> tblTalep1 { get; set; }
    }
}
