//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetSporWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMesaj
    {
        public int mesajid { get; set; }
        public string mesajKonu { get; set; }
        public string mesajDetay { get; set; }
        public int mesajGonderenid { get; set; }
        public int mesajAliciid { get; set; }
        public string mesajOkunmaDurumu { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
        public virtual tblKullanici tblKullanici1 { get; set; }
    }
}
