//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetSporWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProgram()
        {
            this.tblAntremanAyrinti = new HashSet<tblAntremanAyrinti>();
        }
    
        public int programid { get; set; }
        public Nullable<System.DateTime> programGün { get; set; }
        public Nullable<int> hareketid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAntremanAyrinti> tblAntremanAyrinti { get; set; }
        public virtual tblHareketler tblHareketler { get; set; }
    }
}
