//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetSporWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTalep
    {
        public int talepid { get; set; }
        public string talepTip { get; set; }
        public Nullable<System.DateTime> talepTarihi { get; set; }
        public Nullable<int> talepEden { get; set; }
        public Nullable<int> talepEdilenDanisman { get; set; }
        public Nullable<bool> talepDurum { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
        public virtual tblKullanici tblKullanici1 { get; set; }
    }
}
